### ISSUE TITLE
Add details about Warp

### ISSUE THREAD

**Issue by fiestajetsam** [fiestajetsam/draft-gruessing-moq-requirements#20]
Luke Curley has written [another specification](https://datatracker.ietf.org/doc/draft-lcurley-warp/). It's QUIC based, using CMAF for encapsulation, stream based, has no ALPN amongst other features. That said, it should be included in the "prior art" section of the document.

**Comment by SpencerDawkins** [comment]
Agreed!

**Comment by kixelated** [comment]
Some things worth considering, but you guys decide what is worth mentioning.

Warp is the only protocol that is not frame based. Instead it attempts to map the GoP structure to QUIC streams. High quality media is basically linear within a GoP in order to maximize compression, which fits very nicely with QUIC's streams. There's no point delivering frames out of order if they cannot be decoded out of order.

Warp uses prioritization instead of deadlines to achieve dynamic latency. This removes the need for feedback outside of QUIC ACKs and a whole class of problems caused by dropped/delayed feedback.

Warp uses CMAF segments for full compatibility with HLS/DASH, avoiding transmuxing on edge or at origin.

Warp uses the full suite of QUIC functionality. This includes fragmentation, congestion control, flow control, streams (multiplexing + cancellation), etc. Some other protocols use QUIC datagrams and disable everything else, effectively using QUIC as a complex DTLS replacement.

Warp supports a bidirectional API using QUIC streams however this was not in scope for the first version of the draft. I wanted to avoid bike shedding to focus instead on the above features.

Warp uses WebTransport at the moment, but we can decide if it's better suited for native QUIC (with ALPN) or even HTTP/3. Warp would even work over HTTP/2 albeit with additional head-of-line blocking.
