### ISSUE TITLE
Not all use cases are 'real time'

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#25]
> This document describes the uses cases, requirements, and considerations that should guide the design of the encapsulation of a *real-time* media transport protocol as a payload in the QUIC protocol, that will be used for live media contribution, syndication, and streaming.

This term may imply latency constraints that may not exist in all use cases.  

Further, I wonder if the framing as 'encapsulation of a media transport protocol as a payload' jives with what Victor mentioned during our call -- that part of what's interesting is using QUIC as a transport protocol.

**Comment by SpencerDawkins** [comment]
@afrind - two things (one each, for your two excellent points): 

- this draft started out as a survey of what was being described as "Media Over QUIC" last summer (after the IETF 111 side meeting), then lurched downhill to being focused on RTP over QUIC, and then lurched BACK uphill, but not all the way uphill, to focusing on a subset of what's been proposed under the banner of "MOQ". Thanks for helping us spot places in the draft that haven't completed the trek!
- Agreed about reframing the framing, and if we suck any of the other use cases in - there was a lot of discussion around needing help with gaming for sub-100 ms latencies at the IETF 112 side meeting, so that might happen - the current framing might be even less helpful. 

Definitely worth fixing. Expect a PR soon.

**Comment by kixelated** [comment]
I've been using the phrase "live media", defining it as "media that is actively being produced and consumed". It's not perfect but neither is drawing a numeric latency number in the sand.

**Comment by SpencerDawkins** [comment]
@kixelated - just so that I understand (better) - are you saying that the media is being consumed at (roughly) the rate it's being produced? Any answer is fine, I just want to make sure I know what we're talking about here.
