### ISSUE TITLE
Datagrams aren't required for media transport

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#26]
> and the adoption of  I-D.draft-ietf-quic-datagram, have cleared the way for proposals to use QUIC as a media transport

Streams are equally capable of moving media, though the number of different ways to design a protocol have expanded with the addition of datagrams.

**Comment by kixelated** [comment]
Absolutely. 

It might be worth mentioning that QUIC datagrams in their current state have caveats. They are congestion controlled, elicit acknowledgements, and these acknowledgements does not necessarily mean the packets were processed by the application.

QUIC datagrams certainly have their benefits, but protocols need to be designed to use them properly. Otherwise SRTP and DTLS are better options.
