### ISSUE TITLE
RUSH uses streams intentionally

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#28]
Although it's true that RUSH predates DATAGRAM, streams were an intentional choice as RUSH implementations can leverage standard QUIC library reassembly of messages longer than one MTU.

**Comment by kixelated** [comment]
Absolutely. It's disingenuous to say that RUSH is using QUIC streams because QUIC datagrams didn't exist yet.

QUIC streams provide fragmentation, reliability, flow control, and cancellation (error codes). In fact, you could (but shouldn't) use QUIC streams to deliver individual RTP packets without much downside.

**Comment by fiestajetsam** [comment]
The above commits should fix this, please let me know if I got it wrong.
