### ISSUE TITLE
Finer grained latency considerations

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#29]
The opcons drafts uses 4 bands:

   *  ultra low-latency (less than 1 second)
   *  low-latency live (less than 10 seconds)
   *  non-low-latency live (10 seconds to a few minutes)
   *  on-demand (hours or more)
   
I think these bands lose some granularity that is useful.  For example, a functional video call or interactive game probably needs much less than 1s latency, while low latency live may span lower than 1s in some cases?

**Comment by SpencerDawkins** [comment]
@afrind - that's very true. The opcons draft was scoped for "streaming operators", and although we've talked (in MOPS) about doing a separate draft for low-latency streaming, we haven't done that yet (in MOPS). That may be for the best, if MOQ turns out to be "not ABR, less than 500 ms", or something like that. 

I'm also one of the opcons drafts, so I'm thinking we should add at least one, and probably two, lower-than-ultra-low(!!!) latency bands, and explain why we're doing that. 

I'm assigning this to me, so expect a PR soon.

**Comment by kixelated** [comment]
The industry is terrible at naming things. "ultra-low", "low", "non-low", I mean really? It's all terrible marketing rather than an attempt to classify protocols. I like that the opcons tries to reuse and simplify the terminology but... latency is a complicated.

Some protocols have artificial delays, but for the most part, protocols are defined by their ability to deal with congestion. A protocol like RTMP will be "ultra low-latency" within a datacenter or for a user with a perfect network connection, while it will be "low-latency" for somebody on a cellular connection, while it will be "non-low-latency" for somebody going through a tunnel... all of which depends on the implementation.

At the end of the day, these latency lines in the sand don't add to the discussion. I would rather focus on the use-cases like "having a conversation with someone" rather than arguing over millisecond budgets. Sometimes it's vague, like I consider Twitch to be "reaction latency", but at the end of the day its the use cases that matter.
