### ISSUE TITLE
Add a section talking about what QUIC offers and why that's interesting

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#32]
It may help to have a section that talks about the benefits QUIC brings to the table and why we're considering it for media use cases at all other than "it's there".

**Comment by SpencerDawkins** [comment]
Especially if this draft gets waved around at the BOF, I agree that this will improve the document. I think I can write this (many of the reasons were discussed when we chartered QUIC in 2016, and haven't changed), but if anyone else wants to propose text, that will be fine, too.

**Comment by afrind** [comment]
I don't know if I could write the whole text for why QUIC is interesting for video, but here are some bullets I would include:

1. Because QUIC is based on UDP it doesn't suffer from a number of the performance penalties of TCP. 
2. There are many QUIC libraries to choose from and because it is in user space there is more room for extensible APIs between application and transport (eg: dynamically tweaking congestion control, getting parameters from bandwidth estimation, retransmission and prioritization policies, etc).
3. The model of a QUIC connection includes multiple independent streams which do not HoL block each other.  This can be use for modeling things like audio/video/cc/game input/etc.  A functional QUIC library will automatically handle loss and reordering for stream data.
4. There's an inherent partial reliability in QUIC streams, in that either the sender or receiver can terminate the stream early without affecting the overall connection.
5. With the DATAGRAM extension, further partially reliable models are possible
6. With WebTransport, it will be possible to write libraries or applications in JavaScript.

**Comment by SpencerDawkins** [comment]
That's a really nice summary! I'll start there. Thanks! :yum:

**Comment by kixelated** [comment]
For 1, I wouldn't use the phrase "performance penalties". I think you're referring to QUIC's faster handshake or improved congestion control, but at least right now QUIC is more CPU intensive. That's where my mind jumps where I read "performance".

I would focus on the new API that QUIC provides rather than the incremental advantages over TCP. I don't think anybody would be happy if we took an existing TCP protocol (ex. RTMP, HTTP/2, etc) and proxied it over a single QUIC stream.

**Comment by kixelated** [comment]
All flavors of QUIC:
- QUIC provides an encrypted end-to-end connection between two endpoints. 
- QUIC endpoints can create bidirectional or unidirectional ordered byte streams. 
- QUIC streams are reliable until they are terminated by either endpoint with an error code.
- QUIC streams share congestion and flow control but otherwise do not block each other.
- QUIC endpoints can close the connection with an error code.
- QUIC endpoints can send congestion controlled datagrams below the MTU size via an extension.
- QUIC is supported in browsers via HTTP/3 or WebTransport.

Not available within browsers:
- QUIC is implemented in user-space allowing the sender to customize congestion control and prioritization.
- QUIC connections are established using an ALPN.
- QUIC endpoints can choose and change their connection ID.
- QUIC endpoints can migrate IP address without breaking the connection.
