### ISSUE TITLE
Explain latency target choice

### ISSUE THREAD

**Issue by vasilvv** [fiestajetsam/draft-gruessing-moq-requirements#44]
The current definition of latency targets in the draft is based on specific numeric ranges.  Those do make sense (since they ultimately come from use case requirements), but I believe we should focus more on what consequences those have for the protocol design.

Reflecting on our experience with QUIC used for live video vs QUIC used for video conferencing, my proposed definition of the latency target for live video would be "latency an order of magnitude higher than one RTT".  Two major examples of why this is important:
- When the target latency is on the order of one RTT, it makes sense to use FEC and codec-level packet loss concealment.  When the target latency is in the range of many, many RTTs, selectively retransmitting only lost packets is almost always better than FEC.
- When the target latency is on the order of one RTT, it is impossible to use congestion control schemes like BBR, since BBR has probing mechanisms that rely on temporarily inducing delay and amortizing the consequences of that over multiple RTTs.

I think the first point illustrates nicely why protocols like RTP have low-level control over packetization, while the existing MoQ proposals defer it entirely to the QUIC stack.

**Comment by SpencerDawkins** [comment]
@vasilvv - that's super helpful. It helps us explain a few things - why we need to know this, in order to explain why we're shooting for One Protocol, and why we think the first three use cases in the draft are different (they're all RTPish), and why we're not looking at RTP in the BOF - right now, the draft just says AVTCORE is looking at RTP over QUIC, which really isn't much of a justification, engineering-wise.

**Comment by ianswett** [comment]
Victor's points are well made, though I think picking the boundary of the number of round trips necessary to rely on standard QUIC loss detection is a challenge.  5 RTTs provides almost 5 opportunities to repair a loss, which in my experience is almost always enough.  Similarly, I'd expect it's enough for BBR to complete various probing cycles.

It's also important to understand what RTT we have in mind here.  I think the RTT used to understand what domain you're in is approximately smoothed RTT (not min RTT), because the number of rounds for loss recovery or BBR gain cycling or Cubic packet conservation matter the most.

**Comment by kixelated** [comment]
I agree that the numeric ranges are not useful when designing a protocol but they're useful enough as product requirements. However focusing on the RTT completely misses the point. 

Network latency involves fixed delays (min RTT) but most of it is caused by queuing (primarily congestion control). This includes any queues within the application, the network layer, intermediate routers, and even the receiver. You can think of latency as the "frame RTT" which is decoupled from the packet RTT. Of course the packet RTT is important, but it just doesn't factor in how much data has been queued.

For example, it's just useless to talk about RTMP and HLS/DASH latency in terms of network RTTs. In my opinion, the problem with those protocols is that they impose unnecessary dependencies, making it slow to drop the bitrate to reduce queue sizes. Sending media over a single stream means that every frame depends on every previous frame regardless of the GoP structure (no frame dropping), and it also means that new GoPs are dependent on the previous GoPs (no skipping ahead). WebRTC avoids these unnecessary dependencies which is how it's able to rapidly respond to congestion.

I've been working on a "latency theory" document if any of these ideas are resonating with people. I feel like it's too early though, and we should be focusing on the use-cases and requirements instead.

**Comment by SpencerDawkins** [comment]
@kixelated - please let me know when you think it's not too early to focus on "latency theory". I'd love to know more (in particular, I'd love to know if I'd be able to contribute effectively to that important topic). 

Just filing this away for now, as you suggest.
